### ISSUE TITLE
[MS-25] Whitelabel chokes on missing services

### ISSUE THREAD

**Issue by hermanmedsleuth** [medsleuthinc/aws-whitelabel#17]
Observed in the build log for DryRun (AWS log group [`/aws/codebuild/DryRunCB-Gk0MF33HK1Vv`](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/codebuild/DryRunCB-Gk0MF33HK1Vv;stream=345e3008-ac68-45cb-b77c-cc8a72709c4f)).
```
...
[Container] 2020/09/17 23:51:05 Running command python $CODEBUILD_SRC_DIR_Infrastructure/s4-client/make-service-config.py > config/service-config.yml
[Container] 2020/09/17 23:51:05 Running command cat config/service-config.yml
ServiceConfig:
- name: demo
  s3: com-medsleuth-j229-demo
- folder: '{$subdomain}.{$domain}'
  name: static
  s3: com-medsleuth-j229-static
- lambda-arn: cf-j229:RedirectMobileB3LambdaFunctionQualifiedArn
  name: redirectMobileB3
- name: bjs
  serverless: bjs-j229
- name: b3api
  serverless: b3-j229
- name: b3
  s3: com-medsleuth-j229-b3-public
- name: b3-admin
  s3: com-medsleuth-j229-b3-admin-public
[Container] 2020/09/17 23:51:05 Running command cp $ClientConfigFileName config/client-config.yml
[Container] 2020/09/17 23:51:05 Running command [ "$Production" = "yes" ] || export DNS_SANDBOX="$Infra.$InfraDomain"
[Container] 2020/09/17 23:51:05 Running command echo "DNS_SANDBOX=$DNS_SANDBOX"
DNS_SANDBOX=j229.i.mymedsleuth.com
[Container] 2020/09/17 23:51:05 Running command cd config
[Container] 2020/09/17 23:51:05 Running command chmod +x $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh
[Container] 2020/09/17 23:51:05 Running command chmod +x $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.py
[Container] 2020/09/17 23:51:05 Running command $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh
DRY RUN ENGAGED.......
==[ Fetching service details.. ]==============
demo (s3 com-medsleuth-j229-demo): s3://com-medsleuth-j229-demo
static (s3 com-medsleuth-j229-static): s3://com-medsleuth-j229-static/{$subdomain}.{$domain}
redirectMobileB3 (lambda-arn cf-j229:RedirectMobileB3LambdaFunctionQualifiedArn): arn:aws:lambda:us-east-1:785321780735:function:cf-j229-redirectMobileB3:17
bjs (serverless bjs-j229): Traceback (most recent call last):
  File "/codebuild/output/src786/src/s3/02/aws-whitelabel.py", line 9, in <module>
    main()
  File "/codebuild/output/src786/src/s3/02/whitelabel/core.py", line 1158, in main
    discover_services(yaml.get('ServiceConfig', yaml.get('serviceconfig')))
  File "/codebuild/output/src786/src/s3/02/whitelabel/core.py", line 127, in discover_services
    url = ([item for item in l if item['OutputKey'] == 'ServiceEndpoint'][0]['OutputValue'])
IndexError: list index out of range
[Container] 2020/09/17 23:51:05 Command did not exit successfully $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh exit status 1
[Container] 2020/09/17 23:51:05 Phase complete: BUILD State: FAILED
...
```
The problem is that the bjs-j229 ServerLess&trade; deployment no longer has a web API endpoint, due to the removal of the requisition service.

ref: [MS-25], medsleuthinc/b.java#229

[MS-25]: https://medsleuth.atlassian.net/browse/MS-25

**Comment by hermanmedsleuth** [comment]
There are 2 things wrong here.
- make-service-config.py includes the bjs service group even though it no longer has a web API gateway.
- aws-whitelabel.py _assumes_ that the CloudFormation stack description contains a `ServiceEndpoint` element

**Comment by hermanmedsleuth** [comment]
The python code set in the aws-whitelable repo is definitely rather non-standard, although it does work. Since any future diagnostics and debugging should at least originate in AWS, the logging should be optimized for that environment.

**Comment by ficcaglia** [comment]
I don't think we really even need whitelabel do we?  AWS now support
wildcard SSL certs and whitelabel as I recall was designed mostly due to
having limits on # SSL certs you could provision or assign to CFront, or
something like that.  Maybe it was that CFront didn't allow rewrite on
requests to multiple domains.  Not sure but I think all that is now
supported.

before whitelabel we just had a cloudformation template for each domain and
r53 records pointing to each CFront.  I would review that and/or google -
it seems like it's very possible to do:
https://aws.amazon.com/premiumsupport/knowledge-center/multiple-domains-https-cloudfront/

**Comment by hermanmedsleuth** [comment]
I don't know about the certs. These whitelabel updates are related to construction/configuration of the cloudfront distributions, which are required for testing.

**Comment by jyaucs** [comment]
I think the whitelabel utility also builds/updates the api gateway resources to the infra on the `s4-client` pipeline.

**Comment by hermanmedsleuth** [comment]
Since the CloudFront distributions are now being created successfully, this issue can be closed as resolved.

**Comment by jyaucs** [comment]
Similar issue updating on infra `pre-prod`

[codebuild log](https://console.aws.amazon.com/codesuite/codebuild/785321780735/projects/DryRunCB-yMWuZMIgE493/build/DryRunCB-yMWuZMIgE493%3A67958a14-73db-491b-a213-47cb6b9643a1/?region=us-east-1)

```
[Container] 2020/10/13 00:57:21 Running command cd config
--
104 |  
105 | [Container] 2020/10/13 00:57:21 Running command chmod +x $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh
106 |  
107 | [Container] 2020/10/13 00:57:21 Running command chmod +x $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.py
108 |  
109 | [Container] 2020/10/13 00:57:21 Running command $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh
110 | DRY RUN ENGAGED.......
111 | ==[ Fetching service details.. ]==============
112 | demo (s3 com-medsleuth-pre-prod-demo): s3://com-medsleuth-pre-prod-demo
113 | static (s3 com-medsleuth-pre-prod-static): s3://com-medsleuth-pre-prod-static/{$subdomain}.{$domain}
114 | redirectMobileB3 (lambda-arn cf-preprod:RedirectMobileB3LambdaFunctionQualifiedArn): arn:aws:lambda:us-east-1:785321780735:function:cf-preprod-redirectMobileB3:6
115 | bjs (serverless bjs-preprod): Traceback (most recent call last):
116 | File "/codebuild/output/src117/src/s3/01/aws-whitelabel.py", line 9, in <module>
117 | main()
118 | File "/codebuild/output/src117/src/s3/01/whitelabel/core.py", line 1144, in main
119 | discover_services(yaml.get('ServiceConfig', yaml.get('serviceconfig')))
120 | File "/codebuild/output/src117/src/s3/01/whitelabel/core.py", line 123, in discover_services
121 | url = ([item for item in l if item['OutputKey'] == 'ServiceEndpoint'][0]['OutputValue'])
122 | IndexError: list index out of range
123 |  
124 | [Container] 2020/10/13 00:57:21 Command did not exit successfully $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh exit status 1
125 | [Container] 2020/10/13 00:57:21 Phase complete: BUILD State: FAILED
126 | [Container] 2020/10/13 00:57:21 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh. Reason: exit status 1
127 | [Container] 2020/10/13 00:57:21 Entering phase POST_BUILD
128 | [Container] 2020/10/13 00:57:21 Phase complete: POST_BUILD State: SUCCEEDED
129 | [Container] 2020/10/13 00:57:21 Phase context status code:  Message:
130 | [Container] 2020/10/13 00:57:21 Expanding base directory path: .
131 | [Container] 2020/10/13 00:57:21 Assembling file list
132 | [Container] 2020/10/13 00:57:21 Expanding .
133 | [Container] 2020/10/13 00:57:22 Expanding file paths for base directory .
134 | [Container] 2020/10/13 00:57:22 Assembling file list
135 | [Container] 2020/10/13 00:57:22 Expanding config/*
136 | [Container] 2020/10/13 00:57:22 Found 2 file(s)
```
