### ISSUE TITLE
import errors due to ancient boto3

### ISSUE THREAD

**Issue by hermanmedsleuth** [medsleuthinc/aws-whitelabel#24]
The following build error is observed.
```
[Container] 2024/05/16 19:47:27.147547 Running command $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh
Traceback (most recent call last):
  File "/codebuild/output/src632/src/s3/01/aws-whitelabel.py", line 7, in <module>
    from whitelabel import main
  File "/codebuild/output/src632/src/s3/01/whitelabel/__init__.py", line 1, in <module>
    from .core import main
  File "/codebuild/output/src632/src/s3/01/whitelabel/core.py", line 14, in <module>
    import boto3
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/compat.py", line 25, in <module>
    from botocore.exceptions import MD5UnavailableError
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/exceptions.py", line 15, in <module>
    from botocore.vendored import requests
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/vendored/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/vendored/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/vendored/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/vendored/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/vendored/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 9, in <module>
    from ._collections import HTTPHeaderDict
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/root/.pyenv/versions/3.11.8/lib/python3.11/collections/__init__.py)
```

**Comment by hermanmedsleuth** [comment]
Original requirement: boto3>=1.7.17

**Comment by jyaucs** [comment]
@hermanmedsleuth this repo was renamed to `aws-whitelabel-fork-20240519` to keep backups of all related issues and PRs (these metadata types cannot be transferred to new repo per Github). A new private clone of this repo (tested working with devqa pipeline) is available now for review. Thanks!

https://github.com/medsleuthinc/aws-whitelabel

ref: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork
